# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_download = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download.setGeometry(QtCore.QRect(520, 30, 121, 41))
        self.btn_download.setObjectName("btn_download")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 59, 16))
        self.label.setObjectName("label")
        self.ldt_link = QtWidgets.QLineEdit(self.centralwidget)
        self.ldt_link.setGeometry(QtCore.QRect(140, 40, 371, 21))
        self.ldt_link.setObjectName("ldt_link")
        self.btn_opendir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_opendir.setGeometry(QtCore.QRect(520, 80, 121, 41))
        self.btn_opendir.setObjectName("btn_opendir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionzhuji = QtWidgets.QAction(MainWindow)
        self.actionzhuji.setObjectName("actionzhuji")
        self.action123 = QtWidgets.QAction(MainWindow)
        self.action123.setObjectName("action123")
        self.action123_2 = QtWidgets.QAction(MainWindow)
        self.action123_2.setObjectName("action123_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_download.setText(_translate("MainWindow", "开始下载"))
        self.label.setText(_translate("MainWindow", "文库链接"))
        self.btn_opendir.setText(_translate("MainWindow", "打开下载路径"))
        self.actionzhuji.setText(_translate("MainWindow", "zhuji"))
        self.action123.setText(_translate("MainWindow", "123"))
        self.action123_2.setText(_translate("MainWindow", "123"))
