# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 601, 295))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "关于"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\'; font-size:16pt;\">我是「</span><span style=\" font-family:\'Helvetica Neue\'; font-size:16pt; font-weight:600;\">Job Yan</span><span style=\" font-family:\'Helvetica Neue\'; font-size:16pt;\">」，终身学习爱好者，一个热爱技术、干货多多的 Coder。</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PingFang SC\'; font-size:16pt;\">「</span><span style=\" font-family:\'Helvetica Neue\'; font-size:14pt;\">Job Yan</span><span style=\" font-family:\'PingFang SC\'; font-size:16pt;\">」专注人工智能技术与编程技术知识分享。</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PingFang SC\'; font-size:16pt;\">乐享技术，乐享生活：技术、乐趣、财富、生活。</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/weixin/weixin.png\" width=\"350\" /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Hiragino Sans GB\',\'Microsoft YaHei\',\'Arial\',\'sans-serif\'; font-size:16pt; font-weight:600; color:#000000;\">      程序的一些说明：</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'PingFang SC\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">本软件会永久开源并且永不收费，仅供喜欢爬虫技术的小伙伴们学习使用；</li>\n"
"<li style=\" font-family:\'PingFang SC\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">软件可能会由于各种原因而不能使用，请不要依赖此软件；</li>\n"
"<li style=\" font-family:\'PingFang SC\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">本次开发的软件仅支持<span style=\" font-family:\'Helvetica Neue\';\"> PPT </span>文件和<span style=\" font-family:\'Helvetica Neue\';\"> PDF </span>文件的下载，暂不支持<span style=\" font-family:\'Helvetica Neue\';\"> WORD </span>文件和<span style=\" font-family:\'Helvetica Neue\';\"> TXT </span>文件的下载；</li>\n"
"<li style=\" font-family:\'PingFang SC\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">软件爬取到的文件和文库中的原文件是有区别的，以<span style=\" font-family:\'Helvetica Neue\';\"> PPT </span>类型的文件为例，我们在文档页面看到的内容其实是<span style=\" font-family:\'Helvetica Neue\';\"> PPT </span>经过渲染后的图片。所以我们可以利用<span style=\" font-family:\'Helvetica Neue\';\"> Python </span>等编写爬虫脚本，爬取网页中的相关图片，再将这些图片合并成<span style=\" font-family:\'Helvetica Neue\';\"> PDF </span>文档。如果想要获取可编辑的<span style=\" font-family:\'Helvetica Neue\';\"> PPT </span>文件，可能需要你用「钞能力」支持一下文库。 </li></ol></body></html>"))
